using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AutoInstrument.Generator;

/// <summary>All StringBuilder code generation for the interceptor source file.</summary>
internal static class CodeEmitter
{
    private const int DefaultDepth = 1;

    internal static void EmitCombinedFile(
        SourceProductionContext spc,
        ImmutableArray<InstrumentedMethodInfo?> methods,
        ImmutableArray<InterceptCallSite?> sites,
        string? defaultActivitySourceName = null,
        int tagNamingConvention = 0,
        int globalDepth = DefaultDepth)
    {
        {
            methods = methods.Select(m =>
            {
                if (m is null) return m;
                var updated = m;
                if (defaultActivitySourceName is not null && m.DefaultActivitySourceName is null)
                    updated = updated with { DefaultActivitySourceName = defaultActivitySourceName };
                if (tagNamingConvention != 0)
                    updated = updated with { TagNamingConvention = tagNamingConvention };
                if (m.Depth < 0)
                    updated = updated with { Depth = globalDepth };
                return updated;
            }).ToImmutableArray();

            sites = sites.Select(s =>
            {
                if (s is null) return s;
                var updatedMethod = s.Method;
                if (defaultActivitySourceName is not null && s.Method.DefaultActivitySourceName is null)
                    updatedMethod = updatedMethod with { DefaultActivitySourceName = defaultActivitySourceName };
                if (tagNamingConvention != 0)
                    updatedMethod = updatedMethod with { TagNamingConvention = tagNamingConvention };
                if (s.Method.Depth < 0)
                    updatedMethod = updatedMethod with { Depth = globalDepth };
                return updatedMethod == s.Method ? s : s with { Method = updatedMethod };
            }).ToImmutableArray();
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoInstrument");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // Parameter is unread");
        sb.AppendLine("#pragma warning disable CS1998 // Async method lacks 'await' operators");
        sb.AppendLine("#pragma warning disable CS8603 // Possible null reference return");
        sb.AppendLine();

        if (!sites.IsDefaultOrEmpty)
        {
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
            sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
            sb.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
            sb.AppendLine("    {");
            sb.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
            sb.AppendLine("        {");
            sb.AppendLine("            _ = version;");
            sb.AppendLine("            _ = data;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("namespace AutoInstrument.Generated");
        sb.AppendLine("{");

        var sourceNames = new System.Collections.Generic.HashSet<string>();
        if (!methods.IsDefaultOrEmpty)
        {
            foreach (var m in methods)
                if (m is not null) sourceNames.Add(m.EffectiveActivitySourceName);
        }
        if (!sites.IsDefaultOrEmpty)
        {
            foreach (var s in sites)
                if (s is not null) sourceNames.Add(s.Method.EffectiveActivitySourceName);
        }

        if (sourceNames.Count > 0)
        {
            sb.AppendLine("    file static class ActivitySources");
            sb.AppendLine("    {");
            foreach (var name in sourceNames.OrderBy(n => n))
            {
                var fieldName = "__autoInstrumentSource_" + Sanitize(name);
                sb.AppendLine($"        internal static readonly global::System.Diagnostics.ActivitySource {fieldName}");
                sb.AppendLine($"            = new(\"{Escape(name)}\");");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        if (!sites.IsDefaultOrEmpty)
        {
            var byMethod = sites.Where(s => s != null)
                .GroupBy(s => $"{s!.Method.FullyQualifiedClassName}.{s.Method.MethodName}")
                .ToArray();

            sb.AppendLine("    file static class AutoInstrumentInterceptors");
            sb.AppendLine("    {");

            int methodIndex = 0;
            foreach (var group in byMethod)
            {
                var siteList = group.ToList();
                var first = siteList[0]!;
                var method = first.Method;
                var sourceName = method.EffectiveActivitySourceName;
                var sourceField = "__autoInstrumentSource_" + Sanitize(sourceName);
                var spanName = method.EffectiveSpanName;
                var activityKind = KindToString(method.Kind);

                foreach (var site in siteList)
                {
                    sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({site!.LocationVersion}, \"{site.LocationData}\")] // {site.DisplayLocation}");
                }

                var wrapperName = $"__Intercept_{method.ClassName}_{method.MethodName}_{methodIndex}";
                var isInstance = !first.IsStaticCall;

                var paramParts = new System.Collections.Generic.List<string>();
                if (isInstance)
                {
                    paramParts.Add($"this {first.ReceiverType} __self");
                }
                foreach (var p in method.Parameters)
                {
                    var prefix = p.RefKind is not null ? p.RefKind + " " : "";
                    paramParts.Add($"{prefix}{p.Type} {p.Name}");
                }
                var paramStr = string.Join(", ", paramParts);

                var argParts = new System.Collections.Generic.List<string>();
                foreach (var p in method.Parameters)
                {
                    var prefix = p.RefKind switch
                    {
                        "ref" => "ref ",
                        "out" => "out ",
                        "in" => "in ",
                        _ => ""
                    };
                    argParts.Add($"{prefix}{p.Name}");
                }
                var argStr = string.Join(", ", argParts);

                var asyncKeyword = method.IsAwaitable ? "async " : "";
                var returnType = method.ReturnType;

                sb.AppendLine($"        internal static {asyncKeyword}{returnType} {wrapperName}({paramStr})");
                sb.AppendLine("        {");

                var callExpr = isInstance ? $"__self.{method.MethodName}({argStr})" : $"{method.FullyQualifiedClassName}.{method.MethodName}({argStr})";
                var awaitExpr = method.IsAwaitable ? "await " : "";

                if (method.Condition is not null)
                {
                    var condAccess = isInstance ? $"__self.{method.Condition}" : $"{method.FullyQualifiedClassName}.{method.Condition}";
                    sb.AppendLine($"            if (!{condAccess})");
                    if (method.ReturnsVoid || (!method.HasGenericReturn && method.IsAwaitable))
                    {
                        sb.AppendLine("            {");
                        sb.AppendLine($"                {awaitExpr}{callExpr};");
                        sb.AppendLine("                return;");
                        sb.AppendLine("            }");
                    }
                    else
                    {
                        sb.AppendLine($"                return {awaitExpr}{callExpr};");
                    }
                    sb.AppendLine();
                }

                sb.AppendLine($"            if (!ActivitySources.{sourceField}.HasListeners())");
                if (method.ReturnsVoid || (!method.HasGenericReturn && method.IsAwaitable))
                {
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {awaitExpr}{callExpr};");
                    sb.AppendLine("                return;");
                    sb.AppendLine("            }");
                }
                else
                {
                    sb.AppendLine($"                return {awaitExpr}{callExpr};");
                }
                sb.AppendLine();

                if (method.LinkTo is not null)
                {
                    sb.AppendLine($"            var __links = new[] {{ new global::System.Diagnostics.ActivityLink({method.LinkTo}) }};");
                    sb.AppendLine($"            using var __activity = ActivitySources.{sourceField}");
                    sb.AppendLine($"                .StartActivity(\"{Escape(spanName)}\", {activityKind}, default(global::System.Diagnostics.ActivityContext), links: __links);");
                }
                else
                {
                    sb.AppendLine($"            using var __activity = ActivitySources.{sourceField}");
                    sb.AppendLine($"                .StartActivity(\"{Escape(spanName)}\", {activityKind});");
                }
                sb.AppendLine();

                var taggable = method.Parameters
                    .Where(p => TagFiltering.ShouldTagParameter(p, method) && p.RefKind != "out")
                    .ToList();

                var tagMembers = method.TagMembers.Where(_ => isInstance).ToList();

                if (taggable.Count > 0 || tagMembers.Count > 0)
                {
                    sb.AppendLine("            if (__activity is not null)");
                    sb.AppendLine("            {");
                    foreach (var p in taggable)
                    {
                        if (p.IsComplex && p.Properties.Length > 0)
                        {
                            EmitPropertyTags(sb, p.Name, p.Name, p.Properties,
                                method.Skip, method.Fields, p.NoInstrumentProperties,
                                method.MethodName, method.TagNamingConvention);
                        }
                        else
                        {
                            var tagName = TagFiltering.FormatTagName(method.MethodName, p.Name, null, method.TagNamingConvention);
                            sb.AppendLine($"                __activity.SetTag(\"{Escape(tagName)}\", {p.Name});");
                        }
                    }
                    foreach (var tm in tagMembers)
                    {
                        if (tm.IsComplex && tm.Properties.Length > 0)
                        {
                            var baseName = tm.TagName ?? tm.MemberName.ToLowerInvariant();
                            EmitTagMemberPropertyTags(sb, $"__self.{tm.MemberName}", baseName,
                                tm.Properties, tm.Skip, tm.Fields);
                        }
                        else
                        {
                            var tagName = tm.TagName ?? tm.MemberName.ToLowerInvariant();
                            sb.AppendLine($"                __activity.SetTag(\"{Escape(tagName)}\", __self.{tm.MemberName});");
                        }
                    }
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }

                if (method.RecordException)
                {
                    sb.AppendLine("            try");
                    sb.AppendLine("            {");

                    if (method.ReturnsVoid || (!method.HasGenericReturn && method.IsAwaitable))
                    {
                        sb.AppendLine($"                {awaitExpr}{callExpr};");
                        if (method.RecordSuccess)
                        {
                            sb.AppendLine("                __activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);");
                        }
                    }
                    else
                    {
                        sb.AppendLine($"                var __result = {awaitExpr}{callExpr};");
                        if (method.RecordReturnValue)
                        {
                            sb.AppendLine($"                __activity?.SetTag(\"{method.MethodName.ToLowerInvariant()}.return_value\", __result?.ToString());");
                        }
                        if (method.RecordSuccess)
                        {
                            sb.AppendLine("                __activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);");
                        }
                        sb.AppendLine("                return __result;");
                    }

                    sb.AppendLine("            }");
                    sb.AppendLine("            catch (global::System.Exception __ex)");
                    sb.AppendLine("            {");

                    if (method.IgnoreCancellation)
                    {
                        sb.AppendLine("                if (__ex is not global::System.OperationCanceledException)");
                        sb.AppendLine("                {");
                        sb.AppendLine("                    if (__activity is not null)");
                        sb.AppendLine("                    {");
                        sb.AppendLine("                        __activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, __ex.Message);");
                        sb.AppendLine("                        __activity.AddEvent(new global::System.Diagnostics.ActivityEvent(\"exception\",");
                        sb.AppendLine("                            tags: new global::System.Diagnostics.ActivityTagsCollection");
                        sb.AppendLine("                            {");
                        sb.AppendLine("                                { \"exception.type\", __ex.GetType().FullName },");
                        sb.AppendLine("                                { \"exception.message\", __ex.Message },");
                        sb.AppendLine("                                { \"exception.stacktrace\", __ex.ToString() }");
                        sb.AppendLine("                            }));");
                        sb.AppendLine("                    }");
                        sb.AppendLine("                }");
                    }
                    else
                    {
                        sb.AppendLine("                if (__activity is not null)");
                        sb.AppendLine("                {");
                        sb.AppendLine("                    __activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, __ex.Message);");
                        sb.AppendLine("                    __activity.AddEvent(new global::System.Diagnostics.ActivityEvent(\"exception\",");
                        sb.AppendLine("                        tags: new global::System.Diagnostics.ActivityTagsCollection");
                        sb.AppendLine("                        {");
                        sb.AppendLine("                            { \"exception.type\", __ex.GetType().FullName },");
                        sb.AppendLine("                            { \"exception.message\", __ex.Message },");
                        sb.AppendLine("                            { \"exception.stacktrace\", __ex.ToString() }");
                        sb.AppendLine("                        }));");
                        sb.AppendLine("                }");
                    }

                    sb.AppendLine("                throw;");
                    sb.AppendLine("            }");
                }
                else
                {
                    if (method.ReturnsVoid || (!method.HasGenericReturn && method.IsAwaitable))
                    {
                        sb.AppendLine($"            {awaitExpr}{callExpr};");
                        if (method.RecordSuccess)
                        {
                            sb.AppendLine("            __activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);");
                        }
                    }
                    else
                    {
                        if (method.RecordReturnValue)
                        {
                            sb.AppendLine($"            var __result = {awaitExpr}{callExpr};");
                            sb.AppendLine($"            __activity?.SetTag(\"{method.MethodName.ToLowerInvariant()}.return_value\", __result?.ToString());");
                            if (method.RecordSuccess)
                            {
                                sb.AppendLine("            __activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);");
                            }
                            sb.AppendLine("            return __result;");
                        }
                        else
                        {
                            if (method.RecordSuccess)
                            {
                                sb.AppendLine($"            var __result = {awaitExpr}{callExpr};");
                                sb.AppendLine("            __activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);");
                                sb.AppendLine("            return __result;");
                            }
                            else
                            {
                                sb.AppendLine($"            return {awaitExpr}{callExpr};");
                            }
                        }
                    }

                }

                sb.AppendLine("        }");
                sb.AppendLine();
                methodIndex++;
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        spc.AddSource("AutoInstrumentInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitPropertyTags(StringBuilder sb, string accessPrefix, string paramName,
        EquatableArray<PropertyMetadata> properties, EquatableArray<string> skip, EquatableArray<string> fields,
        EquatableArray<string> noInstrumentProperties, string methodName, int convention,
        System.Collections.Generic.List<string>? pathSegments = null)
    {
        pathSegments ??= new System.Collections.Generic.List<string>();
        foreach (var prop in properties)
        {
            pathSegments.Add(prop.Name);
            var dotPath = $"{paramName}.{string.Join(".", pathSegments)}";
            var access = $"{accessPrefix}?.{prop.Name}";

            if (prop.IsComplex && prop.Properties.Length > 0)
            {
                if (TagFiltering.ShouldTagProperty(dotPath, paramName, skip, fields, noInstrumentProperties))
                {
                    EmitPropertyTags(sb, access, paramName, prop.Properties, skip, fields,
                        noInstrumentProperties, methodName, convention, pathSegments);
                }
            }
            else
            {
                if (TagFiltering.ShouldTagProperty(dotPath, paramName, skip, fields, noInstrumentProperties))
                {
                    var tagName = TagFiltering.FormatTagName(methodName, paramName, pathSegments.ToArray(), convention);
                    sb.AppendLine($"                __activity.SetTag(\"{Escape(tagName)}\", {access});");
                }
            }
            pathSegments.RemoveAt(pathSegments.Count - 1);
        }
    }

    private static void EmitTagMemberPropertyTags(StringBuilder sb, string accessPrefix, string namePrefix,
        EquatableArray<PropertyMetadata> properties, EquatableArray<string> skip, EquatableArray<string> fields,
        System.Collections.Generic.List<string>? pathSegments = null)
    {
        pathSegments ??= new System.Collections.Generic.List<string>();
        foreach (var prop in properties)
        {
            pathSegments.Add(prop.Name);
            var dotPath = string.Join(".", pathSegments);
            var access = $"{accessPrefix}?.{prop.Name}";

            if (prop.IsComplex && prop.Properties.Length > 0)
            {
                if (TagFiltering.ShouldTagMemberProperty(dotPath, skip, fields))
                {
                    EmitTagMemberPropertyTags(sb, access, namePrefix, prop.Properties, skip, fields, pathSegments);
                }
            }
            else
            {
                if (TagFiltering.ShouldTagMemberProperty(dotPath, skip, fields))
                {
                    var tagName = $"{namePrefix}.{string.Join(".", pathSegments.Select(s => s.ToLowerInvariant()))}";
                    sb.AppendLine($"                __activity.SetTag(\"{Escape(tagName)}\", {access});");
                }
            }
            pathSegments.RemoveAt(pathSegments.Count - 1);
        }
    }

    internal static string KindToString(int kind) => kind switch
    {
        1 => "global::System.Diagnostics.ActivityKind.Server",
        2 => "global::System.Diagnostics.ActivityKind.Client",
        3 => "global::System.Diagnostics.ActivityKind.Producer",
        4 => "global::System.Diagnostics.ActivityKind.Consumer",
        _ => "global::System.Diagnostics.ActivityKind.Internal",
    };

    internal static string Sanitize(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) ? c : '_'));

    internal static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
